// This file is generated by GoAdmin CLI adm.
package tables

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "users" => http://localhost:9033/admin/info/users
// "documents" => http://localhost:9033/admin/info/documents
// "flights" => http://localhost:9033/admin/info/flights
// "members" => http://localhost:9033/admin/info/members
// "militants" => http://localhost:9033/admin/info/militants
// "projects" => http://localhost:9033/admin/info/projects
// "vehicles" => http://localhost:9033/admin/info/vehicles
//
// example end
//
var Generators = map[string]table.Generator{

	"users":     GetUsersTable,
	"documents": GetDocumentsTable,
	"flights":   GetFlightsTable,
	"members":   GetMembersTable,
	"militants": GetMilitantsTable,
	"projects":  GetProjectsTable,
	"vehicles":  GetVehiclesTable,

	// generators end
}
